		<!-- Modal reificationModal -->
		<button type="button" class="btn btn-primary hidden" data-toggle="modal" data-target="#reificationModal"></button>
		<div class="modal fade" id="reificationModal" tabindex="-1" role="dialog" aria-labelledby="reificationModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="reificationModalLabel">Création archétype</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						<div class="row" data-input-field="name">
							<div class="col-4">Nom</div>
							<div class="col-8"><input data-field="name" type="text" value=""></div>
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" action="close" data-dismiss="modal">Close</button>
						<button type="button" class="btn btn-primary" action="create">Create</button>
					</div>
				</div>
			</div>
		</div>
