<?php
$json = $this->params()->fromQuery('json') ? $this->params()->fromQuery('json') : $this->params()->fromPost('json', '');
if($json){
    echo $this->content;
    return ;
}

$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')
    ->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no');
$this->headMeta()->appendName('theme-color', 'content="#ffffff');

$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));


$this->headLink()->prependStylesheet($this->assetUrl('common/bootstrap-4.1.3/css/bootstrap.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('common/slick/slick-1.8.1.css'));
$this->headLink()->prependStylesheet($this->assetUrl('analyse/build/app.b2aacfc9.css'));
$this->headLink()->prependStylesheet($this->assetUrl('common/jquery-ui/css/jquery-ui.css'));
$this->headLink()->prependStylesheet($this->assetUrl('common/widgets/modals.css'));
$this->headLink()->prependStylesheet($this->assetUrl('common/w2ui/w2ui-1.5.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('editor/css/editor.css'));
$this->headLink()->prependStylesheet($this->assetUrl('editor/css/diagram.css'));
$this->headLink()->prependStylesheet($this->assetUrl('editor/css/nodeStyleModal.css'));
$this->headLink()->prependStylesheet($this->assetUrl('editor/css/panelEdition.css'));
$this->headLink()->prependStylesheet($this->assetUrl('common/spectrum-colorpicker/spectrum.min.css'));

$this->headScript()->appendFile($this->assetUrl('common/jquery/jquery-3.3.1.min.js'));
$this->headScript()->appendFile($this->assetUrl('common/js/all.min.js'));//fontawesome
$this->headScript()->appendFile($this->assetUrl('common/bootstrap-4.1.3/js/bootstrap.min.js'));
$this->headScript()->appendFile($this->assetUrl('common/js/geoLoc.js'));
$this->headScript()->appendFile($this->assetUrl('common/widgets/orchestrator.js'));
$this->headScript()->appendFile($this->assetUrl('common/widgets/MagicObject.js'));
$this->headScript()->appendFile($this->assetUrl('common/widgets/MagicNode.js'));
$this->headScript()->appendFile($this->assetUrl('common/widgets/PWidgets.js'));
$this->headScript()->appendFile($this->assetUrl('common/widgets/McButton.js'));
$this->headScript()->appendFile($this->assetUrl('common/widgets/McModal.js'));
$this->headScript()->appendFile($this->assetUrl('common/spin/spin.min.js'));
$this->headScript()->appendFile($this->assetUrl('common/d3js/d3.V6.min.js'));
$this->headScript()->appendFile($this->assetUrl('common/js/Proto.js'));
$this->headScript()->appendFile($this->assetUrl('common/js/ProtoAPI.js'));
$this->headScript()->appendFile($this->assetUrl('common/underscore/underscore.js'));
$this->headScript()->appendFile($this->assetUrl('common/jquery-ui/js/jquery-ui.js'));
$this->headScript()->appendFile($this->assetUrl('common/w2ui/w2ui-1.5.min.js'));
$this->headScript()->appendFile($this->assetUrl('common/w2ui/Tabs.js'));
$this->headScript()->appendFile($this->assetUrl('common/spectrum-colorpicker/spectrum.min.js'));
$this->headScript()->appendFile($this->assetUrl('common/render/mustache-2.3.min.js'));
$this->headScript()->appendFile($this->assetUrl('common/omk/OmkDataReader.js'));
$this->headScript()->appendFile($this->assetUrl('common/render/renderEngine.js'));

$this->headScript()->appendFile($this->assetUrl('editor/js/modals/NodeStyleModal.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/modals/ReificationModal.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/objects/StyledObject.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/objects/Archetype.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/objects/NodeArchetype.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/objects/LinkArchetype.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/objects/Instance.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/objects/NodeInstance.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/objects/LinkInstance.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/menu/EditionPanel.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/menu/CreationPanelContainer.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/menu/CreationPanel.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/menu/ContextualMenu.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/diagram/Diagram.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/diagram/DiagramBuilder.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/diagram/DiagramModel.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument/Diagram_argument.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument/DiagramBuilder_argument.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument/DiagramModel_argument.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument/NodeArchetype_argument.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument/NodeInstance_argument.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument/LinkArchetype_argument.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument/LinkInstance_argument.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/force/Diagram_force.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/force/DiagramBuilder_force.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/force/DiagramModel_force.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument_force/Diagram_argument_force.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument_force/DiagramBuilder_argument_force.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument_force/DiagramModel_argument_force.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument_force/NodeArchetype_argument_force.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument_force/NodeInstance_argument_force.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument_force/LinkArchetype_argument_force.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/plugins/argument_force/LinkInstance_argument_force.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/EditorAPI.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/Editor.js'));
$this->headScript()->appendFile($this->assetUrl('editor/js/EditorLayout.js'));

$this->headScript()->appendFile($this->assetUrl('analyse/js/popper.min.js'));
$this->headScript()->appendFile($this->assetUrl('analyse/js/page/Browser.js'));
$this->headScript()->appendFile($this->assetUrl('analyse/js/page/PageAdminRequestAPI.js'));
$this->headScript()->appendFile($this->assetUrl('analyse/js/page/PageAdminRequest.js'));
$this->headScript()->appendFile($this->assetUrl('analyse/js/jsonpath-0.8.0.js'));
$this->headScript()->appendFile($this->assetUrl('analyse/js/request/MagicActionNode.js'));
$this->headScript()->appendFile($this->assetUrl('analyse/js/request/RequestBuilder.js'));
$this->headScript()->appendFile($this->assetUrl('analyse/js/request/RequestAPI.js'));
$this->headScript()->appendFile($this->assetUrl('analyse/js/request/RequestElement.js'));
$this->headScript()->appendFile($this->assetUrl('analyse/js/request/RequestEngine.js'));
$this->headScript()->appendFile($this->assetUrl('analyse/js/request/RequestOperator.js'));
$this->headScript()->appendFile($this->assetUrl('analyse/js/request/PredicateRequest.js'));



$this->trigger('view.layout');

?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
                
    </head>

	<body role="document" class="not-connected ">
        <div id="page-search">
			<!-- header Section Begin -->
			<?php echo $this->partial('polemika-ea/header');?>
            <div id="container">
                <div class="container">
                    <div class="page-content row mb-4 mt-4 mx-0">
                        <div class="col-12">
						<?php echo $this->content; ?>                            
                        </div>
                    </div>
                </div>
            </div>

			<!-- Footer Section Begin -->
			<?php echo $this->partial('polemika-ea/footer');?>


        </div>
				
    </body>
</html>